buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.0.194'
    }
}

apply plugin: 'net.minecraftforge.gradle'

version = '2.1.0'
group = 'com.example.furniturepower'
archivesBaseName = 'furniture-power-1.12.2'
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
mappings = 'stable_39'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'
    compile files('libs/cfm-6.3.2-1.12.2.jar')
}

processResources {
    inputs.property 'version', project.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
